"""Public, UI-independent API for the data-center Agent workbench.

The package surface keeps protocols from :mod:`contracts` distinct from the
injected implementations used by the DC-02 execution layer. Importing this
module only loads definitions; network, database, and Qt work remains behind
explicitly invoked host adapters.
"""

from .contracts import (
    AgentEvent,
    AgentEventEmitter,
    AgentEventType,
    AgentRunResult,
    AgentStatus,
    AgentTurn,
    AgentTurnRequest,
    CancellationToken,
    ModelAdapter as ModelAdapterProtocol,
    ModelDelta,
    QueryRequest,
    QueryResult,
    RunContext,
    ToolCall,
    ToolRegistry as ToolRegistryProtocol,
    ToolResult,
)

# These are the stable protocol names used by AgentRunner. The concrete HTTP
# implementation is exported below as ``StreamingModelAdapter`` so importing
# the package cannot silently replace the protocol with an implementation.
ModelAdapter = ModelAdapterProtocol
ToolRegistry = ToolRegistryProtocol

from .agent import Agent, AgentRunner, DataCenterAgent, run_agent
from .agent_query_tool import AgentQueryTool
from .budget import AgentBudget, Budget, BudgetExceeded, BudgetExhausted, BudgetLimits, BudgetSnapshot
from .engine_adapters import (
    CAPABILITIES,
    ENGINE_CAPABILITIES,
    ENGINE_CAPABILITY_MAP,
    ENGINE_CAPABILITY_MATRIX,
    ENGINE_MAP,
    EngineAdapter,
    EngineCapabilities,
    EngineCapability,
    MONGO_READ,
    MongoAdapter,
    MongoEngineAdapter,
    NOSQL_ENGINES,
    READ_ONLY_QUERY,
    ReadOnlyHook,
    ReadOnlyRequest,
    REDIS_READ,
    RedisAdapter,
    RedisEngineAdapter,
    RELATIONAL_ENGINES,
    RelationalAdapter,
    RelationalEngineAdapter,
    SUPPORTED_ENGINES,
    ReadOnlyQuery as EngineReadOnlyQuery,
    build_engine_adapter,
    create_engine_adapter,
    engine_capabilities,
    get_adapter,
    get_engine_adapter,
    get_engine_capability,
    normalize_engine,
)
from .model_adapter import (
    ModelAdapter as StreamingModelAdapter,
    ModelAdapterError,
    ModelCancelled,
    ModelProtocolError,
    ModelTransportError,
    StreamingTransport,
    UrlLibStreamingTransport,
)
from .nosql_policy import (
    POLICY_VERSION as NOSQL_POLICY_VERSION,
    MONGO_FORBIDDEN_OPERATORS,
    MONGO_PIPELINE_STAGES,
    MONGO_READ_OPERATIONS,
    MONGO_SAFE_EXPRESSIONS,
    MongoReadPolicy,
    NoSQLDecision,
    NoSQLPolicy,
    NoSQLPolicyError,
    REDIS_READ_OPERATIONS,
    RedisReadPolicy,
    is_mongo_read_allowed,
    is_redis_read_allowed,
    reject_mongo_unsafe,
    validate_mongo_call,
    validate_mongo_pipeline,
    validate_mongo_read,
    validate_mongo_request,
    validate_redis_call,
    validate_redis_read,
    validate_redis_request,
)
from .policy import (
    POLICY_VERSION as AGENT_POLICY_VERSION,
    HOST_OVERRIDE_ARGUMENTS,
    MONGO_SAFE_OPERATORS,
    TOOL_ARGUMENTS,
    TOOL_NAMES,
    DataCenterPolicy,
    PolicyDecision,
    decide_tool_call,
    validate_tool_call,
)
from .query_executor import DEFAULT_QUERY_TIMEOUT, DEFAULT_ROW_LIMIT, QueryExecutor, QuerySpec, ReadOnlyQuery
from .query_executor import ReadOnlyQuery as ExecutorReadOnlyQuery
from .result_projection import (
    DEFAULT_MAX_CELL_CHARS,
    DEFAULT_MAX_CUMULATIVE_BYTES,
    DEFAULT_MAX_RESULT_BYTES,
    DEFAULT_MAX_ROWS,
    HARD_MAX_ROWS,
    MAX_FETCH_ROWS,
    ProjectedResult,
    ProjectionBudget,
    ResultProjector,
    project_query_result,
    project_result,
    project_tool_result,
)
from .session_manager import Session, SessionContext, SessionLease, SessionManager
from .sql_policy import POLICY_VERSION as SQL_POLICY_VERSION, SQLDecision, SQLPolicy, validate_sql
from .streaming import (
    IncrementalModelParser,
    IncrementalSSEDecoder,
    ModelStreamParser,
    OpenAIStreamParser,
    SSEEvent,
    SSEParser,
    SSEProtocolError,
    SseParser,
    StreamingError,
    ToolArgumentsError,
    iter_sse_events,
)
from .tool_registry import DataCenterToolRegistry, ToolExecutor, default_tool_definitions


# Both the engine hook and query worker have a historical ``ReadOnlyQuery``
# spelling. Keep the worker request as the package's canonical name and expose
# the hook request with an engine-specific alias.
EngineReadOnlyRequest = ReadOnlyRequest


__all__ = [
    "AGENT_POLICY_VERSION",
    "Agent",
    "AgentBudget",
    "AgentEvent",
    "AgentEventEmitter",
    "AgentEventType",
    "AgentQueryTool",
    "AgentRunResult",
    "AgentRunner",
    "AgentStatus",
    "AgentTurn",
    "AgentTurnRequest",
    "Budget",
    "BudgetExceeded",
    "BudgetExhausted",
    "BudgetLimits",
    "BudgetSnapshot",
    "CAPABILITIES",
    "CancellationToken",
    "DataCenterAgent",
    "DataCenterPolicy",
    "DataCenterToolRegistry",
    "DEFAULT_MAX_CELL_CHARS",
    "DEFAULT_MAX_CUMULATIVE_BYTES",
    "DEFAULT_MAX_RESULT_BYTES",
    "DEFAULT_MAX_ROWS",
    "DEFAULT_QUERY_TIMEOUT",
    "DEFAULT_ROW_LIMIT",
    "ENGINE_CAPABILITIES",
    "ENGINE_CAPABILITY_MAP",
    "ENGINE_CAPABILITY_MATRIX",
    "ENGINE_MAP",
    "EngineAdapter",
    "EngineCapabilities",
    "EngineCapability",
    "EngineReadOnlyQuery",
    "EngineReadOnlyRequest",
    "ExecutorReadOnlyQuery",
    "HARD_MAX_ROWS",
    "HOST_OVERRIDE_ARGUMENTS",
    "IncrementalModelParser",
    "IncrementalSSEDecoder",
    "MAX_FETCH_ROWS",
    "MONGO_FORBIDDEN_OPERATORS",
    "MONGO_PIPELINE_STAGES",
    "MONGO_READ",
    "MONGO_READ_OPERATIONS",
    "MONGO_SAFE_EXPRESSIONS",
    "MONGO_SAFE_OPERATORS",
    "ModelAdapter",
    "ModelAdapterError",
    "ModelAdapterProtocol",
    "ModelCancelled",
    "ModelDelta",
    "ModelProtocolError",
    "ModelStreamParser",
    "ModelTransportError",
    "MongoAdapter",
    "MongoEngineAdapter",
    "MongoReadPolicy",
    "NOSQL_ENGINES",
    "NOSQL_POLICY_VERSION",
    "NoSQLDecision",
    "NoSQLPolicy",
    "NoSQLPolicyError",
    "OpenAIStreamParser",
    "PolicyDecision",
    "ProjectedResult",
    "ProjectionBudget",
    "QueryExecutor",
    "QueryRequest",
    "QueryResult",
    "QuerySpec",
    "READ_ONLY_QUERY",
    "REDIS_READ",
    "REDIS_READ_OPERATIONS",
    "RELATIONAL_ENGINES",
    "ReadOnlyHook",
    "ReadOnlyQuery",
    "ReadOnlyRequest",
    "RedisAdapter",
    "RedisEngineAdapter",
    "RedisReadPolicy",
    "RelationalAdapter",
    "RelationalEngineAdapter",
    "ResultProjector",
    "RunContext",
    "SSEEvent",
    "SSEParser",
    "SSEProtocolError",
    "SQLDecision",
    "SQLPolicy",
    "SQL_POLICY_VERSION",
    "Session",
    "SessionContext",
    "SessionLease",
    "SessionManager",
    "SseParser",
    "StreamingError",
    "StreamingModelAdapter",
    "StreamingTransport",
    "SUPPORTED_ENGINES",
    "TOOL_ARGUMENTS",
    "TOOL_NAMES",
    "ToolArgumentsError",
    "ToolCall",
    "ToolExecutor",
    "ToolRegistry",
    "ToolRegistryProtocol",
    "ToolResult",
    "UrlLibStreamingTransport",
    "build_engine_adapter",
    "create_engine_adapter",
    "decide_tool_call",
    "default_tool_definitions",
    "engine_capabilities",
    "get_adapter",
    "get_engine_adapter",
    "get_engine_capability",
    "is_mongo_read_allowed",
    "is_redis_read_allowed",
    "iter_sse_events",
    "normalize_engine",
    "project_query_result",
    "project_result",
    "project_tool_result",
    "reject_mongo_unsafe",
    "run_agent",
    "validate_mongo_call",
    "validate_mongo_pipeline",
    "validate_mongo_read",
    "validate_mongo_request",
    "validate_redis_call",
    "validate_redis_read",
    "validate_redis_request",
    "validate_sql",
    "validate_tool_call",
]
